activation: elu
alpha: 0.046415888336127774
arch: 2
augmentor:
  _lr: 0.0001
  hidden: 64
  lr: 0.0001
  n_layers: 1
  weight_decay: 0.0005
  optimizer: Adam
batch: 0
batch_size: 0
beta: 0.046415888336127774
dataset: Squirrel
degthres: 0
drop_prt: 0.3763908980400059
dropout: 0.5
epoch: 2000
eta: 0.027825594022071243
evaluate_mode: 1
gnn:
  hidden: 64
  lr: 0.01
  n_layers: 1
  norm_type: None
  weight_decay: 0.0005
  optimizer: Adam
n_trials: 100
patience: 200
split_type: tail
temperature: 1.603671511566729
theta: 0.1291549665014884
use_lcc: true
use_undirected: true
verbose: 0
visualize: 0
with_bias: 1
with_decay: 1
with_gpu: 1
