activation: elu
alpha: 0.21544346900318834
arch: 1
augmentor:
  _lr: 0.01
  hidden: 16
  lr: 0.005
  n_layers: 1
  optimizer: Adam
  weight_decay: 0.0005
batch: 0
beta: 1.0
dataset: ogbn-arxiv
degthres: 0
drop_prt: 0.4
dropout: 0.5
epoch: 2000
eta: 0.1291549665014884
evaluate_mode: 1
gnn:
  hidden: 256
  lr: 0.0005
  n_layers: 2
  norm_type: batchNorm
  optimizer: Adam
  weight_decay: 0.0005
n_trials: 100
patience: 50
split_type: tail
temperature: 1.0
theta: 0.3593813663804626
use_lcc: true
use_undirected: true
verbose: 0
visualize: 0
with_bias: 1
with_decay: 1
with_gpu: 1
