activation: elu
alpha: 0.0774263682681127
arch: 1
augmentor:
  hidden: 64
  lr: 0.0001
  n_layers: 1
  weight_decay: 0.0005
  optimizer: Adam
batch: 0
batch_size: 0
beta: 0.01
dataset: Squirrel
degthres: 0
drop_prt: 0.3763908980400059
dropout: 0.5
epoch: 2000
eta: 0.1291549665014884
evaluate_mode: 1
gnn:
  hidden: 64
  lr: 0.1
  n_layers: 1
  weight_decay: 0.0005
  norm_type: None
  optimizer: Adam
n_trials: 100
patience: 200
split_type: tail
temperature: 1.603671511566729
theta: 0.016681005372000592
use_lcc: true
use_undirected: true
verbose: 0
visualize: 0
with_bias: 1
with_decay: 1
with_gpu: 1
activation: elu