activation: elu
alpha: 0.0774263682681127
arch: 2
augmentor:
  _lr: 0.1
  hidden: 64
  lr: 0.001
  n_layers: 1
  optimizer: Adam
  weight_decay: 0.0005
batch: 0
batch_size: 0
beta: 0.3593813663804626
dataset: Chameleon
degthres: 0
drop_prt: 0.6
dropout: 0.5
epoch: 2000
eta: 0.3593813663804626
evaluate_mode: 1
gnn:
  hidden: 64
  lr: 0.005
  n_layers: 1
  norm_type: None
  optimizer: Adam
  weight_decay: 0.0005
n_trials: 100
patience: 200
split_type: tail
temperature: 1.603671511566729
theta: 0.027825594022071243
use_lcc: true
use_undirected: true
verbose: 0
visualize: 0
with_bias: 1
with_decay: 1
with_gpu: 1
